default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: redtogether_dev

test:
  <<: *default
  database: redtogether_test

production:
  <<: *default
  database: redtogether_prod
